### PR TITLE
Infinite error fix & assorted upgrades

### PR DESCRIPTION
**Pull request by jlamson**
# The bugfix

* [bugfix] [Replace `InfiniteLeaderboardDetails` with `InfiniteLeaderboardStanding`](https://github.com/sergiodias25/Snap_Player_Stats/commit/2c67f9d43e62930788e0477f403976751534cb90) 
    * On commit https://github.com/sergiodias25/Snap_Player_Stats/commit/896f2fd877fcdaacfef95a6f37ddac532879765e, it looks like a fix was added for a change where InfiniteLeaderboard values (standing & rating) were moved up and out of `InfiniteLeaderboardDetails`. 3 lines remove the reference, but the first if check doesn't. This was failing for me (currently high 80s. I've hit infinite before, but not in the current season)
    * **still needs verification**, unless @sergiodias25 can confirm this is the typo I think it is. See the reference below for an example file w/ some added comments on where I _think_ the fields will populate for users in infinite rank. 

Screenshot 2024-05-26 at 10 53 18 PM

## Unrelated tweaks

While fixing this, I added a few other small updates. I may make other PRs for a few more significant tweaks related to mac & testing against static files, but I figured this whitespace and .gitignore change was small enough to just lump in here. If people would prefer they're split out, I can do that too. 

* [chore] [Update .gitignore w/ github recommended](https://github.com/sergiodias25/Snap_Player_Stats/commit/6008a923c8f9173e5e870951ee5ef87a1bfe4273) 
    * Added comment on source, and pasted github's recommended python ignores
    * Updates the `/__pycache__/` ignore to start with `**` so it ignores those folders in a nested fashion.
    * Update stats html file ignore to be flexible on different types and nested folders.
* [chore] [Fix whitespace issue](https://github.com/sergiodias25/Snap_Player_Stats/commit/4e29dfc57692d14d98249b7f7181bdfdd540cfdc)

https://github.com/sergiodias25/Snap_Player_Stats/assets/799143/edbb4c54-4417-4381-a25e-2df527560c5c

### CODE REVIEW

**Comment by macthedev** [comment]
hey @jlamson, is this still waiting to be verified? currently still getting this error when running in vscode:
image

**Comment by jlamson** [comment]
@macthedev is that on main? or on this PR branch? IDK if anyone else has run into it, but I did. This PR should fix the validation check. It's checking for the presence of a different key than it ends up getting to populate that row. .

**Comment by macthedev** [comment]
just on this PR branch for now. have it working myself and am continuing to try some stuff on my fork. Will be willing to contribute to this handy project's growth :)

**Comment by sergiodias25** [comment]
merged into master!

**Pull request merged**
